<?php
/**
 * @file ocmc_mission.module
 */

/**
 * Implements hook_page_attachments_alter().
 *
 * Note: If metatag auto trimming ever gets implemented for D8,
 * remove this hook implementation.
 * Source: https://www.drupal.org/project/metatag/issues/2958193
 */
function ocmc_mission_page_attachments_alter(array &$attachments) {
  // Trim all meta tags to a max of 300 characters.
  if (!empty($attachments['#attached']['html_head'])) {
    // Adjust this as needed.
    $max_length = 300;
//    kint($attachments['#attached']['html_head']);
    foreach ($attachments['#attached']['html_head'] as &$tag) {
      // Only process meta tags with a 'content' attribute, that way it will
      // exclude LINK tags or meta tags which do not have a "content" value.
      if (isset($tag[0]['#tag']) && $tag[0]['#tag'] == 'meta') {
        if ((!isset($tag[0]['#attributes']['schema_metatag']) || (isset($tag[0]['#attributes']['schema_metatag']) && !$tag[0]['#attributes']['schema_metatag'])) && isset($tag[0]['#attributes']['content'])) {
          if (!is_string($tag[0]['#attributes']['content'])) {
            $tag[0]['#attributes']['content'] = (string) $tag[0]['#attributes']['content'];
          }
          if (strlen($tag[0]['#attributes']['content']) > $max_length) {
            // Trim the string three characters shorter than the max so that
            // there is room for the elipses.
            $string = wordwrap($tag[0]['#attributes']['content'], ($max_length - 3));
            $string = explode("\n", $string);
            $tag[0]['#attributes']['content'] = $string[0] . '...';
          }
        }
      }
    }
  }
}
