<?php
/**
 * @file ocmc_mission.module
 */

use Drupal\Core\Config\Config;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_page_attachments_alter().
 *
 * Note: If metatag auto trimming ever gets implemented for D8,
 * remove this hook implementation.
 * Source: https://www.drupal.org/project/metatag/issues/2958193
 */
function ocmc_mission_page_attachments_alter(array &$attachments) {
  // Trim all meta tags to a max of 300 characters.
  if (!empty($attachments['#attached']['html_head'])) {
    // Adjust this as needed.
    $max_length = 300;
    foreach ($attachments['#attached']['html_head'] as &$tag) {
      // Only process meta tags with a 'content' attribute, that way it will
      // exclude LINK tags or meta tags which do not have a "content" value.
      if (isset($tag[0]['#tag']) && $tag[0]['#tag'] == 'meta') {
        if ((!isset($tag[0]['#attributes']['schema_metatag']) || (isset($tag[0]['#attributes']['schema_metatag']) && !$tag[0]['#attributes']['schema_metatag'])) && isset($tag[0]['#attributes']['content'])) {
          if (!is_string($tag[0]['#attributes']['content'])) {
            $tag[0]['#attributes']['content'] = (string) $tag[0]['#attributes']['content'];
          }
          if (strlen($tag[0]['#attributes']['content']) > $max_length) {
            // Trim the string three characters shorter than the max so that
            // there is room for the elipses.
            $string = wordwrap($tag[0]['#attributes']['content'], ($max_length - 3));
            $string = explode("\n", $string);
            $tag[0]['#attributes']['content'] = $string[0] . '...';
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ocmc_mission_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_page_edit_form':
      if (isset($form['#fieldgroups']['group_internal_page_elements'])) {
        $nid = $form_state->getformObject()->getEntity()->id();
        $config = \Drupal::config('system.site');
        $front_uri = $config->get('page.front');
        $is_homepage = FALSE;
        if (preg_match('/node\/(\d+)/', $front_uri, $matches)) {
          $homepage_nid = $matches[1];
          if ($is_homepage = ($nid === $homepage_nid)) {
            $form['#fieldgroups']['group_internal_page_elements']->format_settings['formatter'] = 'closed';
            $form['#fieldgroups']['group_internal_page_elements']->format_settings['classes'] = 'hidden';
          }
        }
      }
    case 'node_page_form':
      if (isset($form['#fieldgroups']['group_homepage_elements']) && (!isset($is_homepage) || !$is_homepage)) {
        $form['#fieldgroups']['group_homepage_elements']->format_settings['formatter'] = 'closed';
        $form['#fieldgroups']['group_homepage_elements']->format_settings['classes'] = 'hidden';
      }
      break;

    case 'missionary_missionary_form':
    case 'missionary_missionary_edit_form':
    case 'missionary_missionary_team_form':
    case 'missionary_missionary_team_edit_form':
    case 'missionary_mission_priest_country_form':
    case 'missionary_mission_priest_country_edit_form':
      // Geolocation field provides a great interface to use leaflet
      // to add location data to an entity, but the leaflet map view
      // requires geofield data. The following uses a custom submit
      // handler to prefill the geofield data with the data from the
      // geolocation field.

      // Add a new submit handler to populate the geofield data with
      // the data from the geo location field.
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          array_unshift($form['actions'][$action]['#submit'], 'ocmc_mission_update_geofield_form_submit');
        }
      }

      // Hide/Disable geofield so that the user doesn't get confused
      // between this field and the geo location field.
      $form['field_geofield']['#access'] = false;
      $form['field_geofield']['#type'] = 'hidden';
      break;

    default:
      break;

  }
}

/**
 * Custom form submit handler.
 * @see ocmc_mission_form_missionary_missionary_edit_form_alter().
 */
function ocmc_mission_update_geofield_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Get field values from the geolocation field.
  $geolocation_value = $form_state->getValue('field_geo_location');
  // Get the array structure from the target field.
  $geofield_value = $form_state->getValue('field_geofield');

  // Prepare the latitude and longitude values for the geofield
  // value array with the values from geolocation field.
  $geofield_value[0]['value']['lat'] = $geolocation_value[0]['lat'];
  $geofield_value[0]['value']['lon'] = $geolocation_value[0]['lng'];

  // Set the value array for geofield.
  $form_state->setValue('field_geofield', $geofield_value);
}

/**
 * Implements hook_leaflet_map_info().
 */
function ocmc_mission_leaflet_map_info_alter(&$map_info) {
  $current_path = \Drupal::service('path.current')->getPath();
  // Homepage and Mission Priests page.
  if ($current_path === '/node/1' || $current_path === '/node/14') {
    $map_info['OSM Mapnik']['settings']['dragging'] = FALSE;
    $map_info['OSM Mapnik']['settings']['touchZoom'] = FALSE;
    $map_info['OSM Mapnik']['settings']['zoomControl'] = FALSE;
    $map_info['OSM Mapnik']['settings']['doubleClickZoom'] = FALSE;
    $map_info['OSM Mapnik']['settings']['maxBounds'] = [
      [
        85,
        -200
      ],
      [
        -85,
        200
      ]
    ];

  }
}

/**
 * Implements template_preprocess_page().
 */
function ocmc_mission_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'ocmc_mission/ocmc-mission-disable-number-input-scrolling';
}

/**
 * Implements hook_views_pre_view().
 */
function ocmc_mission_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() === 'news_articles') {
    $filters = $view->display_handler->getOption('filters');
    if (!empty($filters) && isset($filters['field_missionaries_target_id'])) {
      foreach ($filters['field_missionaries_target_id']['value'] as $key => $filter) {
        unset($filters['field_missionaries_target_id']['value'][$key]);
      }
      $filters['field_missionaries_target_id']['group_info']['group_items'] = _ocmc_mission_get_views_exposed_filters_options_of_missionaries('missionary');
      unset($filters['field_missionaries_target_id']['expose']['placeholder']);
      unset($filters['field_missionaries_target_id']['expose']['min_placeholder']);
      unset($filters['field_missionaries_target_id']['expose']['max_placeholder']);
      $view->display_handler->overrideOption('filters', $filters);
    }
  }
}

/**
 * Helper function to configure a views exposed filters.
 *
 * @param string $bundle_type
 *
 * @return array
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function _ocmc_mission_get_views_exposed_filters_options_of_missionaries($bundle_type) {
  $entities = _ocmc_mission_get_missionary_entity_list($bundle_type);
  $options = [];

  foreach($entities as $id => $entity) {
    $value = $entity->label();

    if (isset($value)) {
      $options[$id] = [
        'title' => $value,
        'operator' => '=',
        'value' => [
          'value' => $id,
          'min' => '',
          'max' => '',
        ]
      ];
    }
  }

  return $options;
}

/**
 * Helper function that returns a list of missionary entity items.
 *
 * @param string $bundle_type
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function _ocmc_mission_get_missionary_entity_list($bundle_type) {
  $ids = \Drupal::entityQuery('missionary')->condition('type', $bundle_type)->execute();
  return \Drupal::entityTypeManager()->getStorage('missionary')->loadMultiple($ids);
}
