api_key: Q2F8xD8W4qAiXuYn
host: null
test_mode: 0
secure_url: 'https://secure.ocmc.org'
non_secure_url: 'http://secure.ocmc.org'
short_name: null
login_name: druminate_user
login_password: 'Sy8rp#!7mqPYkEp'
