server_key: 'AAAAb3j5W_I:APA91bG5zEtqrImSXwV218nPo3-FTJpJRxR-oodhvEPG2Ks8XnlBJoFWUJn8-uciOj0ecURosnFqeOASq183IzAOantuDG-iEHwoKwFFp69NJqceLm_97VPbkSLRMFv_pTMAAq2ppxUI'
sender_id: '478770977778'
_core:
  default_config_hash: '-y1W5TduFDylWCKd_XkEImUVxXq2k8ycQSC8CfCav40'
