server_key: 'AAAA8r29L3o:APA91bGfNVWSp9PeV6wfMae9hSoCbNgtF-hvWBIszM4nLd33RkCrjJADlbOs0uIrKyQlxxOcfeq9Q1n6N2Ki6VbK3TfAC5gOaHzO0jo1PUIjMH_2PrCLPviUaHGqTlXWYsEt_yFVVWzV'
sender_id: '1042565377914'
_core:
  default_config_hash: '-y1W5TduFDylWCKd_XkEImUVxXq2k8ycQSC8CfCav40'
