smtp_on: true
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 60
smtp_username: web@ocmc.org
smtp_password: jgzqqrcsnntxzjns
smtp_from: web@ocmc.org
smtp_fromname: OCMC.org
smtp_client_hostname: ocmc.org
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
